# Generated by Django 2.2.7 on 2019-12-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maestrotrabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cedula', models.IntegerField()),
                ('ficha', models.CharField(max_length=40)),
                ('nomina', models.CharField(max_length=40)),
                ('tipnom', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=40)),
                ('unidad', models.CharField(max_length=40)),
                ('feccre', models.DateTimeField(auto_now_add=True)),
                ('fecact', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
