# Generated by Django 2.2.7 on 2019-12-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonoelite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrotrabajadores',
            name='cia',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maestrotrabajadores',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maestrotrabajadores',
            name='cargo',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='maestrotrabajadores',
            name='ficha',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maestrotrabajadores',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maestrotrabajadores',
            name='nomina',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maestrotrabajadores',
            name='tipnom',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maestrotrabajadores',
            name='unidad',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
